version: '3.8'

services:
  php:
    image: php:8.2-apache
    container_name: workevader_php
    volumes:
      - ./src:/var/www/html
      - ./apache.conf:/etc/apache2/conf-enabled/custom-apache.conf
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=workevader_db
      - MYSQL_USER=workevader_user
      - MYSQL_PASSWORD=secret_password
    networks:
      - workevader-network
    command: bash -c "docker-php-ext-install pdo_mysql && a2enmod rewrite && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: workevader_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_secret
      - MYSQL_DATABASE=workevader_db
      - MYSQL_USER=workevader_user
      - MYSQL_PASSWORD=secret_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - workevader-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: workevader_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_secret
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - workevader-network

volumes:
  db_data:

networks:
  workevader-network:
